### list default
GET http://127.0.0.1:8080/system/role-dept/list

### list search by role_id
GET http://127.0.0.1:8080/system/role-dept/list?role_id=1

### list search by dept_id
GET http://127.0.0.1:8080/system/role-dept/list?dept_id=1

### list search by role_id and dept_id
GET http://127.0.0.1:8080/system/role-dept/list?role_id=1&dept_id=1

### create empty
POST http://127.0.0.1:8080/system/role-dept/create
content-type: application/json

{
}

### create empty role_id
POST http://127.0.0.1:8080/system/role-dept/create
content-type: application/json

{
  "dept_id": 1
}

### create empty dept_id
POST http://127.0.0.1:8080/system/role-dept/create
content-type: application/json

{
  "role_id": 1
}

### create success
POST http://127.0.0.1:8080/system/role-dept/create
content-type: application/json

{
  "role_id": 1,
  "dept_id": 1
}

### create success 1
POST http://127.0.0.1:8080/system/role-dept/create
content-type: application/json

{
  "role_id": 2,
  "dept_id": 2
}

### delete empty
DELETE http://127.0.0.1:8080/system/role-dept/delete
content-type: application/json

{
}

### delete success by dept_id
DELETE http://127.0.0.1:8080/system/role-dept/delete
content-type: application/json

{
  "dept_id": 2
}

### delete success by role_id
DELETE http://127.0.0.1:8080/system/role-dept/delete
content-type: application/json

{
  "role_id": 1
}

### check delete
GET http://127.0.0.1:8080/system/role-dept/list?role_id=1
